import type { AppColors } from "../../../brandTheme";
import type { StyleMap } from "../styleTypes";
import { AUTH_BODY_FONT, AUTH_BODY_FONT_EMPHASIS, AUTH_DISPLAY_FONT } from "./constants";

export const createAuthFormStyles = (colors: AppColors) =>
  ({
    authCard: {
      backgroundColor: colors.panel,
      borderColor: colors.border,
      borderWidth: 1,
      borderRadius: 24,
      paddingHorizontal: 16,
      paddingVertical: 18,
      gap: 12,
      shadowColor: colors.shadow,
      shadowOpacity: 0.08,
      shadowRadius: 14,
      shadowOffset: { width: 0, height: 4 },
      elevation: 3,
      marginTop: -24,
      marginHorizontal: 6,
    },
    authStandaloneCard: {
      marginTop: 0,
      marginHorizontal: 0,
      width: "100%",
      maxWidth: 420,
      alignSelf: "center",
    },
    authEmailForm: {
      width: "100%",
      maxWidth: 420,
      alignSelf: "center",
      gap: 14,
    },
    authEntryCard: {
      gap: 14,
    },
    authCardHeader: {
      gap: 6,
    },
    authSectionEyebrow: {
      color: colors.hero,
      fontSize: 11,
      fontWeight: "800",
      textTransform: "uppercase",
      letterSpacing: 0.9,
    },
    authSectionTitle: {
      color: colors.text,
      fontSize: 22,
      lineHeight: 28,
      fontWeight: "800",
      letterSpacing: -0.4,
    },
    authSectionBody: {
      color: colors.subtext,
      fontSize: 13,
      lineHeight: 20,
    },
    authEntryTitle: {
      fontSize: 22,
      fontWeight: "800",
      color: colors.text,
    },
    authEntrySubtitle: {
      fontSize: 13,
      color: colors.subtext,
      lineHeight: 20,
    },
    authTitle: {
      color: colors.text,
      fontSize: 24,
      fontWeight: "700",
      fontFamily: AUTH_DISPLAY_FONT,
      letterSpacing: -0.6,
    },
    authSubtitle: {
      color: colors.subtext,
      fontSize: 14,
      lineHeight: 21,
      fontFamily: AUTH_BODY_FONT,
      letterSpacing: -0.1,
    },
    authModeRow: {
      marginTop: 6,
      flexDirection: "row",
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.panelAlt,
      padding: 0,
      gap: 2,
      overflow: "hidden",
    },
    authModeButton: {
      flex: 1,
      minHeight: 46,
      borderRadius: 16,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 0,
    },
    authModeButtonContent: {
      width: "100%",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
    },
    authModeButtonActive: {
      backgroundColor: colors.brand,
      borderWidth: 1,
      borderColor: colors.brand,
      shadowColor: colors.shadow,
      shadowOpacity: 0.1,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 4 },
      elevation: 2,
    },
    authModeButtonPressed: {
      backgroundColor: colors.panel,
    },
    authModeButtonIndicator: {
      width: 24,
      height: 24,
      borderRadius: 12,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.panel,
      borderWidth: 1,
      borderColor: colors.border,
    },
    authModeButtonIndicatorActive: {
      borderColor: "rgba(11,15,20,0.08)",
      backgroundColor: "rgba(255,255,255,0.32)",
    },
    authModeButtonText: {
      color: colors.subtext,
      fontSize: 14,
      fontWeight: "800",
      fontFamily: AUTH_BODY_FONT_EMPHASIS,
      letterSpacing: -0.15,
    },
    authModeButtonTextActive: {
      color: colors.brandText,
    },
    authHint: {
      color: colors.subtext,
      fontSize: 13,
      lineHeight: 20,
      fontFamily: AUTH_BODY_FONT,
      letterSpacing: -0.1,
    },
    authFieldGroup: {
      gap: 6,
    },
    authFieldLabel: {
      color: colors.text,
      fontSize: 13,
      fontWeight: "700",
      fontFamily: AUTH_BODY_FONT_EMPHASIS,
      letterSpacing: -0.1,
      marginLeft: 2,
    },
    authInput: {
      height: 50,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.panelAlt,
      color: colors.text,
      paddingHorizontal: 14,
      fontSize: 15,
      fontFamily: AUTH_BODY_FONT,
      letterSpacing: -0.1,
    },
    authInputReadOnly: {
      opacity: 0.74,
    },
    authInputRow: {
      minHeight: 50,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.panelAlt,
      flexDirection: "row",
      alignItems: "center",
      paddingLeft: 14,
    },
    authInputRowReadOnly: {
      opacity: 0.74,
    },
    authInputField: {
      flex: 1,
      minHeight: 50,
      color: colors.text,
      fontSize: 15,
      fontFamily: AUTH_BODY_FONT,
      letterSpacing: -0.1,
      paddingRight: 8,
    },
    authInputTrailingButton: {
      width: 42,
      height: 42,
      marginRight: 4,
      alignItems: "center",
      justifyContent: "center",
    },
    authFieldActionRow: {
      flexDirection: "row",
      justifyContent: "flex-end",
      marginTop: 2,
    },
    authTextButton: {
      minHeight: 28,
      justifyContent: "center",
      paddingHorizontal: 2,
    },
    authTextButtonLabel: {
      color: colors.hero,
      fontSize: 13,
      fontWeight: "700",
      fontFamily: AUTH_BODY_FONT_EMPHASIS,
      letterSpacing: -0.1,
    },
    authTextButtonLabelDisabled: {
      opacity: 0.52,
    },
    authStatusText: {
      fontSize: 12,
      lineHeight: 18,
      marginTop: 2,
    },
    authStatusSuccessText: {
      color: colors.successText,
    },
    authStatusErrorText: {
      color: colors.danger,
    },
    noticeToastWrap: {
      position: "absolute",
      left: 16,
      right: 16,
      zIndex: 1200,
      elevation: 24,
    },
    noticeToast: {
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: 14,
      paddingVertical: 12,
      shadowColor: colors.shadow,
      shadowOpacity: 0.18,
      shadowRadius: 16,
      shadowOffset: { width: 0, height: 8 },
      elevation: 12,
    },
    authVerificationPanel: {
      borderRadius: 20,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.info,
      padding: 14,
      gap: 12,
    },
    authVerificationHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    },
    authVerificationIconWrap: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.panel,
      alignItems: "center",
      justifyContent: "center",
    },
    authVerificationHeaderCopy: {
      flex: 1,
      gap: 2,
    },
    authVerificationEyebrow: {
      color: colors.hero,
      fontSize: 11,
      fontWeight: "800",
      textTransform: "uppercase",
      letterSpacing: 0.8,
    },
    authVerificationTitle: {
      color: colors.text,
      fontSize: 16,
      lineHeight: 22,
      fontWeight: "800",
    },
    authVerificationText: {
      color: colors.text,
      fontSize: 13,
      lineHeight: 20,
    },
    authVerificationSteps: {
      gap: 8,
    },
    authVerificationStepRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 10,
    },
    authVerificationStepBullet: {
      width: 20,
      height: 20,
      borderRadius: 10,
      overflow: "hidden",
      textAlign: "center",
      color: colors.heroText,
      backgroundColor: colors.hero,
      fontSize: 11,
      fontWeight: "800",
      lineHeight: 20,
    },
    authVerificationStepText: {
      flex: 1,
      color: colors.text,
      fontSize: 13,
      lineHeight: 19,
    },
    authInlineActions: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 10,
    },
    authSecondaryButton: {
      minHeight: 42,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.heroRing,
      backgroundColor: colors.panel,
      paddingHorizontal: 14,
      alignItems: "center",
      justifyContent: "center",
    },
    authSecondaryButtonDisabled: {
      opacity: 0.62,
    },
    authSecondaryButtonText: {
      color: colors.text,
      fontSize: 14,
      fontWeight: "700",
      fontFamily: AUTH_BODY_FONT_EMPHASIS,
      letterSpacing: -0.1,
    },
    authSubmitButton: {
      marginTop: 2,
      height: 50,
      borderRadius: 12,
      backgroundColor: colors.brand,
      alignItems: "center",
      justifyContent: "center",
    },
    authSubmitButtonText: {
      fontSize: 15,
      fontWeight: "800",
      color: colors.brandText,
    },
    authEntryHint: {
      fontSize: 12,
      color: colors.subtext,
      lineHeight: 18,
    },
    authDividerRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      marginVertical: 2,
    },
    authDividerLine: {
      flex: 1,
      height: 1,
      backgroundColor: colors.border,
    },
    authDividerText: {
      color: colors.subtext,
      fontSize: 12,
      fontWeight: "700",
      textTransform: "uppercase",
      letterSpacing: 0.8,
    },
    configBlock: {
      borderRadius: 16,
      backgroundColor: colors.panelAlt,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 14,
      gap: 8,
    },
    configCode: {
      color: colors.text,
      fontSize: 13,
      fontWeight: "700",
    },
  }) satisfies StyleMap;
