import type { AppColors } from "../../../brandTheme";
import type { StyleMap } from "../styleTypes";

export const createAuthHeroStyles = (colors: AppColors) =>
  ({
    authHero: {
      overflow: "hidden",
      backgroundColor: colors.hero,
      borderRadius: 30,
      paddingHorizontal: 20,
      paddingVertical: 22,
      minHeight: 320,
      borderWidth: 1,
      borderColor: colors.heroRing,
      shadowColor: colors.shadow,
      shadowOpacity: 0.16,
      shadowRadius: 18,
      shadowOffset: { width: 0, height: 10 },
      elevation: 6,
      width: "100%",
      maxWidth: 420,
      alignSelf: "center",
    },
    authHeroRingLarge: {
      position: "absolute",
      width: 320,
      height: 320,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.heroRing,
      opacity: 0.36,
      right: -110,
      top: -60,
    },
    authHeroRingSmall: {
      position: "absolute",
      width: 180,
      height: 180,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.heroRing,
      opacity: 0.46,
      right: 36,
      top: 42,
    },
    brandBadge: {
      flexDirection: "row",
      alignItems: "center",
      alignSelf: "flex-start",
      gap: 12,
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderRadius: 999,
      backgroundColor: "rgba(255,255,255,0.10)",
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.14)",
      marginBottom: 26,
    },
    brandBadgeTextBlock: {
      gap: 2,
    },
    brandBadgeTitle: {
      color: colors.heroText,
      fontSize: 16,
      fontWeight: "800",
    },
    brandBadgeCaption: {
      color: colors.heroMuted,
      fontSize: 12,
      fontWeight: "600",
    },
    authHeroEyebrow: {
      color: colors.brand,
      fontSize: 12,
      fontWeight: "800",
      textTransform: "uppercase",
      letterSpacing: 1,
      marginBottom: 8,
    },
    authHeroTitle: {
      color: colors.heroText,
      fontSize: 34,
      lineHeight: 40,
      fontWeight: "900",
      maxWidth: 330,
    },
    authHeroBody: {
      color: colors.heroMuted,
      fontSize: 15,
      lineHeight: 22,
      marginTop: 12,
      maxWidth: 330,
    },
    featureRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 10,
      marginTop: 22,
    },
    featurePill: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: "rgba(255,255,255,0.10)",
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.12)",
    },
    featurePillText: {
      color: colors.heroText,
      fontSize: 12,
      fontWeight: "700",
    },
  }) satisfies StyleMap;
