import type { AppColors } from "../../../brandTheme";
import type { StyleMap } from "../styleTypes";

export const createCommunityPostDetailStyles = (colors: AppColors) =>
  ({
    postSummaryRow: {
      marginTop: 1,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.panelAlt,
      paddingHorizontal: 11,
      paddingVertical: 8,
    },
    postSummaryText: {
      color: colors.subtext,
      fontSize: 13,
      fontWeight: "700",
    },
    postMetaBadgesRow: {
      flexDirection: "row",
      gap: 4,
      marginTop: 2,
    },
    postMetaBadge: {
      minHeight: 28,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.panelAlt,
      paddingHorizontal: 10,
      maxWidth: "100%",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 5,
    },
    postMetaBadgePrimary: {
      borderColor: "#BFDBFE",
      backgroundColor: "#EFF6FF",
    },
    postMetaBadgeWarning: {
      borderColor: "#FCD34D",
      backgroundColor: "#FFFBEB",
    },
    postMetaBadgeNeutral: {
      borderColor: "#CBD5E1",
      backgroundColor: "#F8FAFC",
    },
    postMetaBadgeText: {
      color: colors.subtext,
      fontSize: 12,
      fontWeight: "700",
      flexShrink: 1,
    },
    postMetaBadgeTextPrimary: {
      color: "#1D4ED8",
      fontWeight: "800",
    },
    postMetaBadgeTextWarning: {
      color: "#92400E",
      fontWeight: "800",
    },
    postMetaBadgeTextNeutral: {
      color: "#475569",
      fontWeight: "700",
    },
    postWeekdayRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
    },
    postWeekdayChip: {
      flex: 1,
      minWidth: 0,
      height: 24,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.panelAlt,
      alignItems: "center",
      justifyContent: "center",
    },
    postWeekdayChipActive: {
      borderColor: "#94A3B8",
      backgroundColor: colors.panel,
    },
    postWeekdayText: {
      color: colors.subtext,
      fontSize: 10,
      fontWeight: "700",
      letterSpacing: -0.1,
    },
    postWeekdayTextActive: {
      color: colors.text,
      fontWeight: "800",
    },
    postFooterCard: {
      marginTop: 2,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.panelAlt,
      paddingHorizontal: 10,
      paddingVertical: 8,
      gap: 6,
    },
    postFooterItemRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    postFooterLabel: {
      width: 48,
      color: colors.subtext,
      fontSize: 12,
      fontWeight: "700",
    },
    postFooterValue: {
      flex: 1,
      color: colors.text,
      fontSize: 14,
      fontWeight: "800",
    },
    postFooterValueSecondary: {
      color: colors.subtext,
      fontSize: 13,
      fontWeight: "700",
    },
    postFooterDivider: {
      height: 1,
      backgroundColor: colors.border,
    },
    postContactRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      marginTop: 2,
    },
    postContactAction: {
      maxWidth: "100%",
      minWidth: 0,
      minHeight: 32,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: "#BFDBFE",
      backgroundColor: "#EFF6FF",
      paddingHorizontal: 11,
      flexShrink: 1,
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
    },
    postContactActionText: {
      color: "#1D4ED8",
      fontSize: 12,
      fontWeight: "700",
      flexShrink: 1,
    },
    postNote: {
      color: colors.subtext,
      fontSize: 13,
      lineHeight: 18,
    },
    mine: {
      color: colors.text,
      fontSize: 13,
      fontWeight: "700",
    },
    postDetailModalOverlay: {
      flex: 1,
      justifyContent: "center",
      paddingHorizontal: 14,
    },
    postDetailModalBackdrop: {
      position: "absolute",
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      backgroundColor: "rgba(15,23,42,0.48)",
    },
    postDetailModalCard: {
      maxHeight: "86%",
      borderRadius: 20,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.panel,
      paddingHorizontal: 14,
      paddingVertical: 12,
      gap: 10,
    },
    postDetailModalHeaderRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      justifyContent: "space-between",
      gap: 10,
    },
    postDetailModalTitleBlock: {
      flex: 1,
      gap: 2,
      paddingTop: 2,
    },
    postDetailModalTitle: {
      color: colors.text,
      fontSize: 18,
      fontWeight: "800",
      letterSpacing: -0.2,
    },
    postDetailModalSubtitle: {
      color: colors.subtext,
      fontSize: 13,
      fontWeight: "600",
    },
    postDetailModalCloseButton: {
      width: 32,
      height: 32,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.panelAlt,
      alignItems: "center",
      justifyContent: "center",
    },
    postDetailModalContent: {
      gap: 12,
      paddingBottom: 6,
    },
  }) satisfies StyleMap;
