import type { AppColors } from "../../../brandTheme";
import type { StyleMap } from "../styleTypes";

export const createCommunityPostDetailStyles = (colors: AppColors) =>
  ({
    postSummaryRow: {
      marginTop: 1,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.panelAlt,
      paddingHorizontal: 11,
      paddingVertical: 8,
    },
    postSummaryText: {
      color: colors.subtext,
      fontSize: 13,
      lineHeight: 16,
      fontWeight: "700",
      includeFontPadding: false,
      textAlignVertical: "center",
    },
    postMetaBadgesRow: {
      flexDirection: "row",
      gap: 4,
      marginTop: 2,
    },
    postMetaBadge: {
      minHeight: 28,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.panelAlt,
      paddingHorizontal: 10,
      maxWidth: "100%",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 5,
    },
    postMetaBadgePrimary: {
      borderColor: "#BFDBFE",
      backgroundColor: "#EFF6FF",
    },
    postMetaBadgeWarning: {
      borderColor: "#FCD34D",
      backgroundColor: "#FFFBEB",
    },
    postMetaBadgeNeutral: {
      borderColor: "#CBD5E1",
      backgroundColor: "#F8FAFC",
    },
    postMetaBadgeText: {
      color: colors.subtext,
      fontSize: 12,
      lineHeight: 14,
      fontWeight: "700",
      flexShrink: 1,
      includeFontPadding: false,
      textAlignVertical: "center",
    },
    postMetaBadgeTextPrimary: {
      color: "#1D4ED8",
      fontWeight: "800",
    },
    postMetaBadgeTextWarning: {
      color: "#92400E",
      fontWeight: "800",
    },
    postMetaBadgeTextNeutral: {
      color: "#475569",
      fontWeight: "700",
    },
    postWeekdayRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
    },
    postWeekdayChip: {
      flex: 1,
      minWidth: 0,
      height: 26,
      borderRadius: 999,
      borderWidth: 1,
      alignItems: "center",
      justifyContent: "center",
    },
    postWeekdayChipActive: {
      borderColor: "#F59E0B",
      backgroundColor: "#FFF7D6",
    },
    postWeekdayChipInactive: {
      borderColor: colors.border,
      backgroundColor: "#F8FAFC",
    },
    postWeekdayText: {
      color: "#94A3B8",
      fontSize: 10,
      lineHeight: 12,
      fontWeight: "700",
      letterSpacing: -0.1,
      includeFontPadding: false,
      textAlignVertical: "center",
    },
    postWeekdayTextActive: {
      color: colors.brandText,
      fontWeight: "800",
    },
    postFooterCard: {
      marginTop: 2,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.panelAlt,
      paddingHorizontal: 10,
      paddingVertical: 8,
      gap: 6,
    },
    postFooterItemRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    postFooterLabel: {
      width: 48,
      color: colors.subtext,
      fontSize: 12,
      lineHeight: 16,
      fontWeight: "700",
      includeFontPadding: false,
      textAlignVertical: "center",
    },
    postFooterValue: {
      flex: 1,
      color: colors.text,
      fontSize: 14,
      lineHeight: 18,
      fontWeight: "800",
      includeFontPadding: false,
      textAlignVertical: "center",
    },
    postFooterValueSecondary: {
      color: colors.subtext,
      fontSize: 13,
      lineHeight: 18,
      fontWeight: "700",
      includeFontPadding: false,
      textAlignVertical: "center",
    },
    postFooterDivider: {
      height: 1,
      backgroundColor: colors.border,
    },
    postContactRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      marginTop: 2,
    },
    postContactAction: {
      maxWidth: "100%",
      minWidth: 0,
      minHeight: 44,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: "#BFDBFE",
      backgroundColor: "#EFF6FF",
      paddingHorizontal: 11,
      flexShrink: 1,
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
    },
    postContactActionText: {
      color: "#1D4ED8",
      fontSize: 12,
      lineHeight: 16,
      fontWeight: "700",
      flexShrink: 1,
      includeFontPadding: false,
      textAlignVertical: "center",
    },
    postDriverInfoCard: {
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: "#FFFFFF",
      paddingHorizontal: 12,
      paddingVertical: 11,
      gap: 10,
    },
    postDriverInfoHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: 7,
    },
    postDriverInfoTitle: {
      color: colors.text,
      fontSize: 14,
      lineHeight: 18,
      fontWeight: "800",
      includeFontPadding: false,
      textAlignVertical: "center",
    },
    postDriverInfoRows: {
      gap: 8,
    },
    postDriverInfoRow: {
      minHeight: 28,
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    postDriverInfoIconSlot: {
      width: 22,
      height: 22,
      borderRadius: 999,
      backgroundColor: colors.panelAlt,
      alignItems: "center",
      justifyContent: "center",
    },
    postDriverInfoLabel: {
      width: 68,
      color: colors.subtext,
      fontSize: 12,
      lineHeight: 16,
      fontWeight: "700",
      includeFontPadding: false,
      textAlignVertical: "center",
    },
    postDriverInfoValue: {
      flex: 1,
      color: colors.text,
      fontSize: 13,
      lineHeight: 18,
      fontWeight: "800",
      includeFontPadding: false,
      textAlignVertical: "center",
      textAlign: "right",
    },
    postNote: {
      color: colors.subtext,
      fontSize: 13,
      lineHeight: 18,
    },
    mine: {
      color: colors.text,
      fontSize: 13,
      fontWeight: "700",
    },
    postDetailPageCard: {
      backgroundColor: colors.panel,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 16,
      gap: 14,
      shadowColor: colors.shadow,
      shadowOpacity: 0.03,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 1 },
      elevation: 1,
    },
  }) satisfies StyleMap;
